name: Deploy to GitHub Pages
permissions:
  contents: write
  packages: write
on:
  push:
    branches:
      - main  # Or the default branch you're using

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: setting up git credentials
        run: git config --global user.name "vignesh-pandian-p" && git config --global user.email "vigneshpandian0710@gmail.com"
    
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Installing github packages
        run: npm install --save-dev gh-pages

      - name: Build the app
        run: npm run build --production

      - name: Setting up github credentials
        run: git remote set-url origin https://vignesh-pandian-p:${{ secrets.github-login-push }}@github.com/${{ github.repository }}.git
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
